name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: mkdir bin
      run: mkdir bin
    - name: make smoke-sanitize
      run: make smoke=1 sanitize=1
    - name: run
      run: ./bib/regeal.exe
