name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: mkdir bin
      run: mkdir bin
    - name: make sanitize
      run: make sanitize=1
    - name: run
      run: ./bin/regeal.exe

  smoke:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: mkdir bin
      run: mkdir bin
    - name: make sanitize
      run: make sanitize=1 smoke=1
    - name: run
      run: ./bin/regeal.exe
